### ISSUE TITLE
Suggestion about files removal when storage is almost full

### ISSUE THREAD

**Issue by quammy** [kerberos-io/opensource#17]
Hi,

I like very much this project. I think it is a great one!! I plan to use it with my Home Assistant server.

One thing I noticed that I think can be improved (user experience aspect) -

I run kerberos.io on docker and suddenly witnessed all files on the capture folder being removed every 1 min or so.
It turned out that my 450GB SSD had only ~32GB free space. Once I cleaned the recycle bin (~80GB), the phenomenon disappeared.
I guess Kerberos checks free space by percentage - I suggest to do it by actual GB. 32GB are a lot of free space and should not cause such aggressive files deletion.
I also suggest to eliminate older files only. Maybe leave always the newest 50 files or so? Instead of delete them all.

thanks in advanced and cheers!

**Comment by cedricve** [comment]
we'll take that into account in new release (this repo). The issue however is related to kerberos-io/machinery. Thanks @quammy
