### ISSUE TITLE
Prevent Machinery from crashing due not beeing able to connect to camera "Feature suggestion"

### ISSUE THREAD

**Issue by lexustec** [kerberos-io/opensource#19]
I experienced that the machinery is crashing if the camera can not be reached or similar.

in pseudo programming i suggest the following:

try
{
   open camera stream with settings: settings.xml
}
catch (error)
{
    if error == connection failed or not found
     { 
          put error to log and say sorry
          create dummy stream with tiny loop video on 8889
     }
else{

something else happened, spam the logz

}

}

This is extremely helpfull also while buildimng up the Network. especially in container environments.... ( network routing issues)
You can fire up the container and check if You actually see a stream on 8889 without connecting the cam.

greetings

Thomas

**Comment by cedricve** [comment]
we'll take that into account in new release (this repo). The issue however is related to kerberos-io/machinery. Thanks @lexustec
